# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: run-utests
      name: utests
      entry: utest/run.py
      language: python
      additional_dependencies: [jsonschema]
      pass_filenames: false
      always_run: true
      stages: [push]
